export const REQUEST_SCHOOLS_FROM_ST         = 'REQUEST_SCHOOLS_FROM_ST';
export const REQUEST_SCHOOLS_FROM_ST_FAILED  = 'REQUEST_SCHOOLS_FROM_ST_FAILED';
export const RECEIVED_SCHOOLS_FROM_ST         = 'RECEIVED_SCHOOLS_FROM_ST';
export const CLEAR_SCHOOLS                   = 'CLEAR_SCHOOLS';
export const CLEAR_SCHOOLS_COMPLETED         = 'CLEAR_SCHOOLS_COMPLETED';
export const ENABLES_STUB                    = 'ENABLES_STUB';
export const DISABLES_STUB                   = 'DISABLES_STUB';
export const RECEIVE_SCHOOLS_ADD_TO_FAV      = 'RECEIVE_SCHOOLS_ADD_TO_FAV'