export const REQUEST_SCHOOLS_FROM_ST         = 'REQUEST_SCHOOLS_FROM_ST';
export const REQUEST_SCHOOLS_FROM_ST_FAILED  = 'REQUEST_SCHOOLS_FROM_ST_FAILED';
export const RECEIVE_SCHOOLS_FROM_ST         = 'RECEIVE_SCHOOLS_FROM_ST';
export const CLEAR_SCHOOLS                   = 'CLEAR_SCHOOLS';
export const CLEAR_SCHOOLS_COMPLETED         = 'CLEAR_SCHOOLS_COMPLETED';